version: "3"

services:
  app:
    image: node:14
    command: npm start
    restart: unless-stopped
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app:Z
    ports:
      - "80:80"
