name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Setup npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('package-lock.json') }}

      - name: Install packages
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run test
        run: npm test

      - name: Upload coverage
        uses: codecov/codecov-action@v1
